### ISSUE TITLE
Can't get working

### ISSUE THREAD

**Issue by twd3** [doefom/statamic-browser-detect#1]
Does this work locally? I installed fresh Statamic and installed this addon along with a few more and I can't get this to work. To test I'm just putting this into my layout so I can see it work, but nothing renders.
```
        {{ if Browser::isDesktop() }}
        <p>It's a desktop device!</p>
        {{ /if }}
        {{ if browser:isMobile }}
        <p>It's a mobile device!</p>
        {{ /if }}
```

Environment
Application Name: Site Name
Laravel Version: 10.40.0   
PHP Version: 8.2.14        
Composer Version: 2.6.6    
Environment: local
Debug Mode: ENABLED        
URL: blah.test     
Maintenance Mode: OFF      

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log      
Cache: statamic        
Database: mysql        
Logs: stack / single   
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 13
Antlers: runtime       
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.44.0 PRO

Statamic Addons
acquaint-softtech/geo-location: 0.0.2
aryehraber/statamic-captcha: 1.10.0
aryehraber/statamic-logbook: 3.1.0
doefom/statamic-browser-detect: 0.1.1
duncanmcclean/static-cache-manager: 3.1.2
hairylemon-developers/form-guard: 1.0.1
jacksleight/statamic-bard-mutator: 2.3.0
jacksleight/statamic-bard-texstyle: 3.1.4
ndx/statamic-bard-color-picker: 1.2.0
stillat/social-media-image-kit: 1.0.0
stillat/statamic-attribute-renderer: 1.0.0
stoffelio/statamic-404-logger: 1.0.1
teamnovu/statamic-images-missing-alt: 1.0.2

**Comment by doefom** [comment]
Hi @twd3! Thanks for reaching out. `browser:isMobile` should work, you're doing this correctly. I'll take a look at it in the next few days and will keep you posted.

**Comment by twd3** [comment]
Thank you! I'm getting no errors in console or the log.

**Comment by doefom** [comment]
@twd3 Turns out I had an error in the docs, the issue should be fixed by using:
```
{{ if {browser:isMobile} }}
   <p>It's a mobile device!</p>
{{ /if }}
```
instead of
```
{{ if browser:isMobile }}
   <p>It's a mobile device!</p>
{{ /if }}
```

I'll mark this as closed. Feel free to reach out if you need further assistance.
